import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { ManualPaymentCard } from '@/components/manual-payment-card'

export default async function BillingPage() {
  const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)redirect('/login')
  const {data:sub}=await s.from('subscriptions').select('status,current_period_start,current_period_end,cancel_at_period_end').eq('user_id',user.id).eq('plan','manager_monthly').maybeSingle()
  const {data:payments}=await s.from('payment_requests').select('id,amount,currency,payment_method,sender_number,transaction_id,status,reject_reason,created_at,reviewed_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(30)
  const active=!!sub&&['active','trialing'].includes(sub.status)&&!!sub.current_period_end&&new Date(sub.current_period_end)>new Date()
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-green">Billing</p><h1 className="mt-2 text-3xl font-black">Manager Plan</h1><p className="mt-2 text-sm text-muted">৳99/month • one flat • up to 10 invite codes per month.</p></div><ManualPaymentCard active={active} periodEnd={sub?.current_period_end??null}/><section className="card"><div className="flex items-center justify-between"><h2 className="font-semibold">Current plan</h2><span className="rounded-full border border-line px-3 py-1 text-xs font-semibold">{sub?.status??'inactive'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-muted">Plan</p><p className="mt-1 font-semibold">Manager Plan</p></div><div><p className="text-xs text-muted">Status</p><p className="mt-1 font-semibold capitalize">{sub?.status??'inactive'}</p></div><div><p className="text-xs text-muted">Period end</p><p className="mt-1 font-semibold">{sub?.current_period_end?new Date(sub.current_period_end).toLocaleDateString('en-BD'):'—'}</p></div></div></section><section className="card"><h2 className="font-semibold">Payment history</h2><div className="mt-4 space-y-2">{(payments??[]).map((p:any)=><div key={p.id} className="flex flex-col gap-2 rounded-xl border border-line bg-surface-2 p-3 text-sm sm:flex-row sm:items-center sm:justify-between"><div><div className="font-semibold">৳{Number(p.amount).toFixed(2)} • {p.payment_method}</div><div className="mt-1 text-xs text-muted">{new Date(p.created_at).toLocaleString('en-BD')} {p.transaction_id?`• TXN ${p.transaction_id}`:''}</div></div><div className="text-xs font-semibold capitalize">{p.status}{p.reject_reason?` — ${p.reject_reason}`:''}</div></div>)}{!(payments??[]).length&&<p className="text-sm text-muted">No payment requests yet.</p>}</div></section></div>
}
