'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

function normalizeBdPhone(value: string) { const raw=value.replace(/\s+/g,''); if(/^01\d{9}$/.test(raw)) return `+88${raw}`; if(/^8801\d{9}$/.test(raw)) return `+${raw}`; if(/^\+8801\d{9}$/.test(raw)) return raw; return raw }

function friendlyJoinError(message: string) {
  const value = message.toLowerCase()
  if (value.includes('invite_code_expired')) return 'This invite code has expired. Please ask your manager for a new code.'
  if (value.includes('invite_code_already_used')) return 'This invite code has already been used.'
  if (value.includes('invite_code_revoked')) return 'This invite code has been revoked. Please ask your manager for a new code.'
  if (value.includes('flat_locked_subscription_expired')) return 'This flat is currently locked because the manager subscription has expired.'
  return 'That Flat Code is no longer valid. Please check the code and try again.'
}

export default function JoinPage() {
  const supabase=createClient(); const router=useRouter(); const [inviteCode,setInviteCode]=useState(''); const [name,setName]=useState(''); const [contact,setContact]=useState(''); const [method,setMethod]=useState<'phone'|'email'>('email'); const [otp,setOtp]=useState(''); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  async function sendOtp(){setBusy(true);setError('');const code=inviteCode.trim().toUpperCase();if(!/^[A-Z0-9]{6,16}$/.test(code)){setError('Enter a valid Flat Code.');setBusy(false);return}if(method==='phone'&&!/^\+8801\d{9}$/.test(normalizeBdPhone(contact))){setError('Enter a valid Bangladesh mobile number.');setBusy(false);return}if(method==='email'&&!/^\S+@\S+\.\S+$/.test(contact.trim())){setError('Enter a valid email address.');setBusy(false);return}const result=method==='phone'?await supabase.auth.signInWithOtp({phone:normalizeBdPhone(contact),options:{shouldCreateUser:true,data:{full_name:name.trim()||'MealHisab User'}}}):await supabase.auth.signInWithOtp({email:contact.trim().toLowerCase(),options:{shouldCreateUser:true,data:{full_name:name.trim()||'MealHisab User'}}});if(result.error)setError(result.error.message);else setSent(true);setBusy(false)}
  async function verify(){setBusy(true);setError('');const result=method==='phone'?await supabase.auth.verifyOtp({phone:normalizeBdPhone(contact),token:otp.trim(),type:'sms'}):await supabase.auth.verifyOtp({email:contact.trim().toLowerCase(),token:otp.trim(),type:'email'});if(result.error){setError(result.error.message);setBusy(false);return}const {error:joinError}=await supabase.rpc('join_flat_with_code',{p_code:inviteCode.trim().toUpperCase()});if(joinError){setError(friendlyJoinError(joinError.message));setBusy(false);return}router.push('/dashboard');router.refresh()}
  return <main className="min-h-screen bg-canvas px-4 py-10 text-main"><div className="mx-auto max-w-xl"><Link href="/account-type" className="text-sm font-semibold text-muted">← Back</Link><div className="card mt-6 space-y-5"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-green">Join your flat</p><h1 className="mt-2 text-3xl font-black">{sent?'Verify and join':'Enter your Flat Code'}</h1><p className="mt-2 text-sm leading-6 text-muted">{sent?'We sent an email OTP. Verify it to join your flat for free.':'Enter the invite code given by your mess manager. Joining MealHisab is free for members.'}</p></div>{!sent?<div className="space-y-4"><label className="block text-sm font-semibold">Flat Code<input className="input mt-1.5 text-center uppercase tracking-[0.3em]" value={inviteCode} onChange={e=>setInviteCode(e.target.value.toUpperCase())} placeholder="AB7KQ9Z2" maxLength={16} required/></label><label className="block text-sm font-semibold">Name<input className="input mt-1.5" value={name} onChange={e=>setName(e.target.value)} placeholder="Rahim Ahmed"/></label><div className="grid grid-cols-2 gap-2 rounded-2xl bg-surface-2 p-1.5"><button type="button" className={method==='email'?'btn-primary':'btn-secondary'} onClick={()=>setMethod('email')}>Email</button><button type="button" className={method==='phone'?'btn-primary':'btn-secondary'} onClick={()=>setMethod('phone')}>Phone <span className="text-[10px] opacity-75">(optional)</span></button></div><input className="input" value={contact} onChange={e=>setContact(e.target.value)} placeholder={method==='phone'?'+8801712345678':'you@example.com'} />{method==='email'&&<p className="text-xs text-muted">Email OTP is the default and avoids unnecessary SMS cost.</p>}<button className="btn-primary w-full" onClick={sendOtp} disabled={busy}>{busy?'Sending…':'Send OTP'}</button></div>:<div className="space-y-4"><input className="input text-center text-lg tracking-[0.4em]" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} maxLength={6} inputMode="numeric" placeholder="123456" autoFocus/><button className="btn-primary w-full" onClick={verify} disabled={busy||otp.length<4}>{busy?'Joining…':'Verify & join flat'}</button><button className="btn-secondary w-full" onClick={()=>{setSent(false);setOtp('')}}>Change details</button></div>}{error&&<p className="rounded-2xl border border-danger/30 bg-danger/10 p-3 text-sm text-danger" role="alert">{error}</p>}<p className="text-center text-xs text-muted">Joining a flat is free.</p></div></div></main>
}
